openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing
paths:
  /users:
    post:
      summary: Creates a user.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                age:
                  type: number
                  format: int32
                dataSchema:
                  type: string
                  format: uri
                  default: https://example.com/v1/schema.json
                  enum:
                    - https://example.com/v1/schema.json
                    - https://example.co.uk/v1/schema.json

      responses: 
        '201':
          description: Created
